#!/usr/bin/env python3
"""
EQ Offset Header Generator

Reads the MQ symbol database (eq_symbols.json) and generates C++ header
files compatible with eqlib's offset format. This is the final step in
the patch-day workflow:

    1. EQ patches -> new eqgame.exe
    2. eq_patch_diff.py compares old/new, finds moved functions via patterns
    3. Ghidra bridge re-confirms addresses, discovers lost symbols
    4. This script generates the updated offset headers

Usage:
    python3 generate_offsets.py eq_symbols.json --output offsets.h
    python3 generate_offsets.py eq_symbols.json --format eqlib-addresses
    python3 generate_offsets.py eq_symbols.json --validate
"""

import argparse
import json
import sys
from collections import defaultdict
from datetime import datetime


def load_db(path: str) -> dict:
    with open(path, "r") as f:
        return json.load(f)


def generate_header(db: dict, output_format: str = "eqlib-addresses") -> str:
    """Generate C++ header content from symbol database."""
    meta = db.get("metadata", {})
    functions = db.get("functions", {})
    globals_dict = db.get("globals", {})

    build_date = meta.get("eq_build_date", "UNKNOWN")
    build_time = meta.get("eq_build_time", "UNKNOWN")
    gen_date = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    lines = []
    lines.append("// Auto-generated by MacroQuest RE tooling")
    lines.append("// EQ Build: {} {}".format(build_date, build_time))
    lines.append("// Generated: {}".format(gen_date))
    lines.append("// Source DB SHA256: {}".format(meta.get("eq_exe_sha256", "?")[:16]))
    lines.append("//")
    lines.append("// DO NOT EDIT MANUALLY - regenerate from eq_symbols.json")
    lines.append("//")
    lines.append("")

    if output_format == "eqlib-addresses":
        lines.append("#pragma once")
        lines.append("")
        lines.append('#define __ExpectedVersionDate "{}"'.format(build_date))
        lines.append('#define __ExpectedVersionTime "{}"'.format(build_time))
        lines.append("")

        # Group by category
        by_category = defaultdict(list)
        for name, info in sorted(functions.items()):
            cat = info.get("category", "other")
            by_category[cat].append((name, info))
        for name, info in sorted(globals_dict.items()):
            cat = info.get("category", "other")
            by_category[cat].append((name, info))

        category_order = [
            "version", "memcheck", "compression", "module_enum", "process_enum",
            "rendering", "display", "input", "keybind", "ui", "chat",
            "player", "spell", "inventory", "login", "other",
        ]

        for cat in category_order:
            items = by_category.get(cat, [])
            if not items:
                continue

            lines.append("// " + "=" * 60)
            lines.append("// {}".format(cat.upper().replace("_", " ")))
            lines.append("// " + "=" * 60)

            for name, info in items:
                addr = info.get("address", "0x0")
                confidence = info.get("confidence", "?")
                notes = info.get("notes", "")

                # Convert RVA string to integer
                try:
                    rva_int = int(addr, 16)
                except (ValueError, TypeError):
                    rva_int = 0

                comment_parts = []
                if confidence != "confirmed":
                    comment_parts.append(confidence)
                if notes:
                    comment_parts.append(notes)
                comment = " // " + ", ".join(comment_parts) if comment_parts else ""

                # Use the eqlib naming convention
                if name.startswith("__"):
                    lines.append("#define {:45s} 0x{:X}{}".format(
                        name + "_x", rva_int, comment))
                else:
                    lines.append("#define {:45s} 0x{:X}{}".format(
                        name, rva_int, comment))

            lines.append("")

    elif output_format == "ida-idc":
        # Generate IDC script for IDA Pro
        lines.append('#include <idc.idc>')
        lines.append("")
        lines.append("static main()")
        lines.append("{")
        lines.append('    auto base = 0x{:X};'.format(
            int(meta.get("image_base", "0x140000000"), 16)))

        for name, info in sorted(functions.items()):
            addr = info.get("address", "0x0")
            try:
                rva = int(addr, 16)
            except (ValueError, TypeError):
                continue
            lines.append('    MakeNameEx(base + 0x{:X}, "{}", SN_NOWARN);'.format(rva, name))

        for name, info in sorted(globals_dict.items()):
            addr = info.get("address", "0x0")
            try:
                rva = int(addr, 16)
            except (ValueError, TypeError):
                continue
            lines.append('    MakeNameEx(base + 0x{:X}, "{}", SN_NOWARN);'.format(rva, name))

        lines.append("}")

    elif output_format == "ida-python":
        # Generate IDAPython script
        lines = [
            "# MQ Symbol Import for IDA Pro",
            "# EQ Build: {} {}".format(build_date, build_time),
            "",
            "import idc",
            "import idautils",
            "import ida_name",
            "",
            "base = idaapi.get_imagebase()",
            "",
        ]

        for name, info in sorted(functions.items()):
            addr = info.get("address", "0x0")
            try:
                rva = int(addr, 16)
            except (ValueError, TypeError):
                continue
            cat = info.get("category", "other")
            lines.append('ida_name.set_name(base + 0x{:X}, "{}", ida_name.SN_NOWARN)  # {}'.format(
                rva, name, cat))

        lines.append("")
        lines.append("print('Imported {} MQ symbols')".format(
            len(functions) + len(globals_dict)))

    return "\n".join(lines) + "\n"


def validate_db(db: dict) -> int:
    """Validate a symbol database for completeness and consistency."""
    functions = db.get("functions", {})
    globals_dict = db.get("globals", {})
    meta = db.get("metadata", {})

    errors = 0
    warnings = 0

    # Check metadata
    if not meta.get("eq_build_date"):
        print("ERROR: Missing eq_build_date in metadata")
        errors += 1
    if not meta.get("eq_build_time"):
        print("ERROR: Missing eq_build_time in metadata")
        errors += 1

    # Critical symbols that MUST be present for MQ to function
    critical_symbols = [
        "__MemChecker0", "__MemChecker1", "__EncryptPad0",
        "__ModuleList", "__ProcessList",
        "__compress_block", "__decompress_block",
    ]

    for sym in critical_symbols:
        if sym not in functions and sym not in globals_dict:
            print("ERROR: Critical symbol missing: {}".format(sym))
            errors += 1
        else:
            info = functions.get(sym) or globals_dict.get(sym, {})
            addr = info.get("address", "0x0")
            if addr == "0x0" or not addr:
                print("ERROR: Critical symbol has no address: {}".format(sym))
                errors += 1
            if info.get("confidence") == "low":
                print("WARNING: Critical symbol has low confidence: {}".format(sym))
                warnings += 1

    # Check for zero addresses
    for name, info in list(functions.items()) + list(globals_dict.items()):
        addr = info.get("address", "")
        if not addr or addr == "0x0":
            print("WARNING: {} has no address".format(name))
            warnings += 1

    # Check for duplicate addresses
    addr_map = defaultdict(list)
    for name, info in list(functions.items()) + list(globals_dict.items()):
        addr = info.get("address", "")
        if addr and addr != "0x0":
            addr_map[addr].append(name)

    for addr, names in addr_map.items():
        if len(names) > 1:
            print("WARNING: Duplicate address {}: {}".format(addr, ", ".join(names)))
            warnings += 1

    print()
    print("Validation: {} errors, {} warnings".format(errors, warnings))
    print("Functions: {}, Globals: {}".format(len(functions), len(globals_dict)))

    confirmed = sum(1 for f in functions.values() if f.get("confidence") == "confirmed")
    with_pattern = sum(1 for f in functions.values() if f.get("pattern"))
    print("Confirmed: {}/{} ({:.0f}%)".format(
        confirmed, len(functions),
        100 * confirmed / max(len(functions), 1)))
    print("Have patterns: {}/{} ({:.0f}%)".format(
        with_pattern, len(functions),
        100 * with_pattern / max(len(functions), 1)))

    return errors


def main():
    parser = argparse.ArgumentParser(
        description="Generate eqlib-compatible offset headers from symbol database"
    )
    parser.add_argument("db", help="Path to eq_symbols.json")
    parser.add_argument("--output", "-o", help="Output file (default: stdout)")
    parser.add_argument("--format", "-f", default="eqlib-addresses",
                        choices=["eqlib-addresses", "ida-idc", "ida-python"],
                        help="Output format")
    parser.add_argument("--validate", "-v", action="store_true",
                        help="Validate the database instead of generating")
    args = parser.parse_args()

    db = load_db(args.db)

    if args.validate:
        errors = validate_db(db)
        sys.exit(1 if errors > 0 else 0)

    output = generate_header(db, args.format)

    if args.output:
        with open(args.output, "w") as f:
            f.write(output)
        print("Written to: {}".format(args.output), file=sys.stderr)
    else:
        print(output)


if __name__ == "__main__":
    main()
